### ISSUE TITLE
Enable plugin on a type of page instead of individually?

### ISSUE THREAD

**Issue by colmoneill** [multicolor-rgb/newgalleryfolder-for-bluditcms#1]
Would there be a way of enabling the plugin on all article pages? I tried inserting a '*' in the form field where the slug list goes, but that did not work. I would like to have the plugin be active on all article pages, without having to add the slug to the list.

Thanks for the plugin though, it is working great for me so far.

All the best!

**Comment by multicolor-rgb** [comment]
Ok i will add if empty, shows on all pages :)

**Comment by multicolor-rgb** [comment]
v3 release :)
