### ISSUE TITLE
Adding a caption to the images 

### ISSUE THREAD

**Issue by colmoneill** [multicolor-rgb/newgalleryfolder-for-bluditcms#2]
This might have to interact with the image-upload function of bludit, but would it be possible to add a caption to the images when they are in the viewer? Maybe simply via an Alt tag or the likes?

Thanks again, all the best.

**Comment by multicolor-rgb** [comment]
i think about alt generate from name every file. What do you think?

**Comment by multicolor-rgb** [comment]
v3 release :)
