### ISSUE TITLE
v4: thumbnails have wrong orientation

### ISSUE THREAD

**Issue by chuckgit123** [multicolor-rgb/newgalleryfolder-for-bluditcms#4]
Hi! I noticed that in v4 the orientation of some thumbnails is wrong. The images affected were directly uploaded from iOS and I read in the [Bludit Community Support Forum](https://forum.bludit.org/viewtopic.php?t=1727) that this might be sometimes an issue, but the suggested solution is not very practical for me because I like to be able to directly post via iPhone.

Anyway, with v3 I don't have this issue.

**Comment by multicolor-rgb** [comment]
Please tell me, thumbnails have ok orientation on default v4 version? Maybe problem has on still beta cms not my plugin.

**Comment by chuckgit123** [comment]
Hm - just to be sure I made myself clear: when I said v3 I was talking about the version of the plugin, that is: v3 of the plugin shows correct orientation, v4 of the plugin doesn't. I tested both on Bludit v3.13.1.

**Comment by multicolor-rgb** [comment]
oooh this because previous version give thumbnails with original photos, next version get from thumbnails folder from bludit. I will create optional settings if you have problem with that.

**Comment by chuckgit123** [comment]
> I will create optional settings if you have problem with that.

Cool, that would be great! :smile:

**Comment by multicolor-rgb** [comment]
v 5.0 release :)

**Comment by multicolor-rgb** [comment]
v 5.0 release :)
